export enum AgentStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}

export enum CFSChargedOn {
  UPON_REQUEST = "UPON_REQUEST",
  WEEKDAY = "WEEKDAY",
  WEEKEND_PUBLIC_HOLIDAY = "WEEKEND_PUBLIC_HOLIDAY",
  PUBLIC_HOLIDAY = "PUBLIC_HOLIDAY",
  PER_DAY = "PER_DAY",
  PER_CONTAINER = "PER_CONTAINER",
  OVERTIME = "OVERTIME"
}

export enum CFSContainerStatus {
  OUTSIDE_BONDED = "OUTSIDE_BONDED",
  PLUGGED_ON = "PLUGGED_ON",
  PLUGGED_OFF = "PLUGGED_OFF",
  ON_VESSEL = "ON_VESSEL",
  IN_STORAGE = "IN_STORAGE",
  TO_BE_REPAIRED = "TO_BE_REPAIRED",
  NEED_REPAIR = "NEED_REPAIR",
  HOUSEKEEPING = "HOUSEKEEPING",
  CLEANING = "CLEANING",
  STUFFING = "STUFFING",
  PENDING_PLUG_ON = "PENDING_PLUG_ON",
  PENDING_PLUG_OFF = "PENDING_PLUG_OFF",
  PENDING_LOADING_CABLING = "PENDING_LOADING_CABLING",
  PENDING_STORAGE = "PENDING_STORAGE",
  HOUSEKEEPING_CLEANING = "HOUSEKEEPING_CLEANING",
  HOUSEKEEPING_STUFFING = "HOUSEKEEPING_STUFFING",
  CLEANING_STUFFING = "CLEANING_STUFFING",
  HOUSEKEEPING_CLEANING_STUFFING = "HOUSEKEEPING_CLEANING_STUFFING",
  IN_USE = "IN_USE",
  PENDING_RETURN = "PENDING_RETURN"
}

export enum CfsContainerType {
  DRY = "DRY",
  CHILLER = "CHILLER",
  FREEZER = "FREEZER",
  CHILLER_FREEZER = "CHILLER_FREEZER"
}

export enum CrewTransferPortOfOrigin {
  KSB = "KSB",
  KTSB = "KTSB",
  WW = "WW"
}

export enum CrewTransferRequestType {
  SIGN_ON = "SIGN_ON",
  SIGN_OFF = "SIGN_OFF"
}

export enum CrewTransferSignOnStatus {
  SIGN_ON = "SIGN_ON",
  SIGN_OFF = "SIGN_OFF",
  SIGN_OFF_ENFORCED = "SIGN_OFF_ENFORCED"
}

export enum ImigJlMohStatus {
  PASS = "PASS",
  REJECT = "REJECT"
}

export enum AccountStatusEnum {
  RELEASED = "RELEASED",
  BLOCKED = "BLOCKED"
}

export enum Block_Status {
  ENDORSED = "ENDORSED",
  PENDING = "PENDING"
}

export enum Credit_Status {
  ACTIVE = "ACTIVE",
  BLOCKED = "BLOCKED"
}

export enum CustomerPriceGroupEnum {
  PAC = "PAC",
  NON_PAC = "NON_PAC",
  EOS = "EOS",
  KPK = "KPK"
}

export enum CustomerStatusEnum {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}

export enum CustomerUserType {
  REQUISITIONER = "REQUISITIONER",
  ENDORSER = "ENDORSER",
  AUTHORISED = "AUTHORISED"
}

export enum MachineryPreferences {
  NO_PREFERENCES = "NO_PREFERENCES",
  KSB_ASSETS_ONLY = "KSB_ASSETS_ONLY"
}

export enum NewRequestEnum {
  ALLOW = "ALLOW",
  ON_HOLD = "ON_HOLD"
}

export enum AttendanceDaily {
  ATTEND = "ATTEND",
  NOT_ATTEND = "NOT_ATTEND",
  WFH = "WFH"
}

export enum Clock_In_Type {
  CLOCK_IN = "CLOCK_IN",
  CLOCK_OUT = "CLOCK_OUT",
  ABSENT = "ABSENT"
}

export enum Employee_Status_Type {
  AVAILABLE = "AVAILABLE",
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  NOT_ATTEND = "NOT_ATTEND",
  CHECK_IN = "CHECK_IN",
  REQUEST = "REQUEST",
  ADDITIONAL = "ADDITIONAL",
  LIGHT_DUTY = "LIGHT_DUTY",
  MC_EL_AL = "MC_EL_AL",
  OFF = "OFF",
  BALANCE = "BALANCE"
}

export enum Employee_Type {
  OPERATOR = "OPERATOR",
  ADMIN = "ADMIN",
  PLANNER = "PLANNER",
  SUPPLIER = "SUPPLIER"
}

export enum EmployeeDesignation {
  BO = "BO",
  CH = "CH"
}

export enum EmployeeStatusWork {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}

export enum ExternalItemStatus {
  BOOKED = "BOOKED",
  COMPLETED = "COMPLETED"
}

export enum Gang_Type_Status {
  A = "A",
  B = "B"
}

export enum StatusGang {
  START = "START",
  STOP = "STOP"
}

export enum GroupEnum {
  A = "A",
  A1 = "A1",
  A2 = "A2",
  A3 = "A3",
  A4 = "A4",
  A5 = "A5",
  A6 = "A6",
  A7 = "A7",
  A8 = "A8",
  A9 = "A9",
  A10 = "A10",
  A11 = "A11",
  A12 = "A12",
  A13 = "A13",
  A14 = "A14",
  B = "B",
  B1 = "B1",
  B2 = "B2",
  B3 = "B3",
  B4 = "B4",
  B5 = "B5",
  B6 = "B6",
  B7 = "B7",
  B8 = "B8",
  B9 = "B9",
  B10 = "B10",
  B11 = "B11",
  B12 = "B12",
  B13 = "B13",
  B14 = "B14"
}

export enum GroupStatusEnum {
  AVAILABLE = "AVAILABLE",
  NON_AVAILABLE = "NON_AVAILABLE"
}

export enum Groupscopework {
  GENERAL_CARGO = "GENERAL_CARGO",
  FUEL_WATER = "FUEL_WATER",
  BULK_CARGO = "BULK_CARGO",
  OTHER_BULK = "OTHER_BULK"
}

export enum Decision_Site {
  BERTH = "BERTH",
  NON_BERTH = "NON_BERTH"
}

export enum Group_Site_Status {
  ON = "ON",
  OFF = "OFF"
}

export enum Site_Particular_Status {
  NON_BERTH = "NON_BERTH",
  BERTH = "BERTH"
}

export enum ICWAvailabilityEnum {
  NORMAL = "NORMAL",
  DECANT = "DECANT",
  EMPCON = "EMPCON",
  EMPTY_BACK_OF_EMPCON = "EMPTY_BACK_OF_EMPCON"
}

export enum ICWBillingStatusEnum {
  UNPAID_NORMAL = "UNPAID_NORMAL",
  UNPAID_OVERDUE = "UNPAID_OVERDUE",
  PAID = "PAID"
}

export enum ICWBillingTypeEnum {
  AUTO = "AUTO",
  MANUAL = "MANUAL"
}

export enum ICWCollectReturn {
  COLLECT = "COLLECT",
  RETURN = "RETURN"
}

export enum ICWRequestTypeEnum {
  STORAGE_REQUEST = "STORAGE_REQUEST",
  TRANSFER_REQUEST = "TRANSFER_REQUEST",
  ADDITIONAL_SERVICES = "ADDITIONAL_SERVICES",
  HANDLING_IN = "HANDLING_IN",
  HANDLING_OUT = "HANDLING_OUT"
}

export enum ICWServiceTypeEnum {
  DECANT = "DECANT",
  REPACK = "REPACK"
}

export enum ICWTypeOfChargeEnum {
  RENTAL = "RENTAL",
  PER_UOM = "PER_UOM"
}

export enum InvoiceTypesEnum {
  ENDORSE_REQUEST_STORAGE = "ENDORSE_REQUEST_STORAGE",
  ENDORSE_REQUEST_TRANSFER = "ENDORSE_REQUEST_TRANSFER",
  ENDORSE_ADDITIONAL_SERVICE = "ENDORSE_ADDITIONAL_SERVICE",
  PERIODIC_RATE = "PERIODIC_RATE"
}

export enum RequestStorageStatusEnum {
  SUBMITTED = "SUBMITTED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ENDORSED = "ENDORSED",
  INVOICED = "INVOICED",
  CANCELLED = "CANCELLED"
}

export enum RequestTransferStatusEnum {
  INITIATED = "INITIATED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ENDORSED = "ENDORSED",
  INVOICED = "INVOICED",
  CANCELLED = "CANCELLED",
  SUBMITTED = "SUBMITTED"
}

export enum DocumentTypeEnum {
  INVOICE = "INVOICE",
  PROCESS_NOTE = "PROCESS_NOTE",
  REMINDER = "REMINDER",
  PRINTED_REQUEST = "PRINTED_REQUEST",
  OTHERS = "OTHERS"
}

export enum ICYSActiveStatus {
  YES = "YES",
  NO = "NO"
}

export enum InvoiceTypeEnum {
  ENDORSE_GOODS_RECEIVING = "ENDORSE_GOODS_RECEIVING",
  ENDORSE_GOODS_RELEASE = "ENDORSE_GOODS_RELEASE",
  PERIODIC_RATE = "PERIODIC_RATE"
}

export enum StatusGRAEnum {
  SUBMITTED = "SUBMITTED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ENDORSED = "ENDORSED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}

export enum StatusGRNEnum {
  INITIATED = "INITIATED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ENDORSED = "ENDORSED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}

export enum StorageDurationEnum {
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY"
}

export enum StorageTypeEnum {
  YARD = "YARD",
  WHAREHOUSE = "WHAREHOUSE"
}

export enum ItemType {
  BOUY = "BOUY",
  ANCHOR = "ANCHOR",
  CCU = "CCU"
}

export enum CompanyBranch {
  PBKSB_CFS = "PBKSB_CFS",
  PBKSB_CHE = "PBKSB_CHE",
  PBKSB_CHO = "PBKSB_CHO",
  PBKSB_CWY = "PBKSB_CWY",
  PBKSB_DVO = "PBKSB_DVO",
  PBKSB_ISS = "PBKSB_ISS",
  PBKSB_SEC = "PBKSB_SEC",
  PBKSB_WMS = "PBKSB_WMS",
  PBKSB_SWM = "PBKSB_SWM",
  PBKSB_ICYS = "PBKSB_ICYS",
  PBKSB_ICW = "PBKSB_ICW",
  PBKSB_MHE = "PBKSB_MHE",
  PBKSB_MARINE = "PBKSB_MARINE",
  PBKSB_CWCY = "PBKSB_CWCY",
  PBKSB_CREW = "PBKSB_CREW"
}

export enum HistoryStatus {
  PREVIOUS = "PREVIOUS",
  UPDATED = "UPDATED"
}

export enum StatusInvoice {
  CREATED = "CREATED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  SENT = "SENT",
  CANCELLED = "CANCELLED",
  VERIFIED = "VERIFIED"
}

export enum Cancellation {
  NO = "NO",
  YES = "YES"
}

export enum CancellationType {
  NORMAL = "NORMAL",
  LATE = "LATE",
  NONE = "NONE"
}

export enum DocumentStatus {
  ORIGINAL = "ORIGINAL",
  AMENDMENT = "AMENDMENT"
}

export enum Job_MHE_ServiceType {
  MACHINERY = "MACHINERY",
  MANPOWER = "MANPOWER",
  EQUIPMENT = "EQUIPMENT",
  EXTERNAL_ITEM = "EXTERNAL_ITEM",
  OTHER_MACHINERY = "OTHER_MACHINERY",
  MARINE = "MARINE"
}

export enum Job_Service_Type {
  MHE = "MHE",
  MARINE = "MARINE",
  WAREHOUSE = "WAREHOUSE",
  PSB = "PSB"
}

export enum JobStatus {
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  SUBMITTED = "SUBMITTED",
  BOOKED = "BOOKED",
  ENDORSED = "ENDORSED",
  NEW = "NEW",
  SENT = "SENT",
  ASSIGNED = "ASSIGNED",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  WAITING_LIST = "WAITING_LIST",
  REQUEST_AMEND = "REQUEST_AMEND",
  INITIATED = "INITIATED",
  VERIFIED = "VERIFIED",
  INVOICE_CREATED = "INVOICE_CREATED",
  INVOICE_PENDING_APPROVAL = "INVOICE_PENDING_APPROVAL",
  INVOICE_CHANGES = "INVOICE_CHANGES"
}

export enum SessionTimeType {
  SESSION_1 = "SESSION_1",
  SESSION_2 = "SESSION_2",
  SESSION_3 = "SESSION_3",
  SESSION_4 = "SESSION_4"
}

export enum ViewInListBoxEnum {
  YES = "YES",
  NO = "NO"
}

export enum Console_Status {
  YES = "YES",
  NO = "NO"
}

export enum MachineCategory {
  TR = "TR",
  EQ = "EQ",
  CR = "CR",
  PRMV = "PRMV",
  GC = "GC",
  MR = "MR"
}

export enum MachineOwnerShip {
  KSB = "KSB",
  CONTRACT = "CONTRACT"
}

export enum MachineStatus {
  AVAILABLE = "AVAILABLE",
  IN_USE = "IN_USE",
  NOT_AVAILABLE = "NOT_AVAILABLE",
  REQUEST = "REQUEST",
  BREAKINGDOWN = "BREAKINGDOWN",
  GREASING = "GREASING"
}

export enum MachineType {
  FORKLIFT = "FORKLIFT",
  CRANE = "CRANE",
  PRIME_MOVER = "PRIME_MOVER",
  OTHER_MHE = "OTHER_MHE",
  COMBILIF = "COMBILIF",
  SKYLIFT = "SKYLIFT",
  TRUCK = "TRUCK",
  SWEEPER = "SWEEPER",
  WEIGH_BRIDE = "WEIGH_BRIDE",
  TRAILER = "TRAILER",
  MARINE_HOST = "MARINE_HOST",
  GARBAGE_TRUCK = "GARBAGE_TRUCK",
  GRASS_CUTTER = "GRASS_CUTTER",
  EQUIPMENT = "EQUIPMENT"
}

export enum QuotationStatus {
  YES = "YES",
  NO = "NO"
}

export enum CategoryEnum {
  MACHINERY = "MACHINERY",
  MANPOWER = "MANPOWER"
}

export enum ChildStatusEnum {
  YES = "YES",
  NO = "NO"
}

export enum DisplayStatusEnum {
  YES = "YES",
  NO = "NO"
}

export enum MachineOperatorEnum {
  MACHINE = "MACHINE",
  OPERATOR = "OPERATOR"
}

export enum MachineryToolsEnum {
  AVAILABLE = "AVAILABLE",
  GREASING = "GREASING",
  BREAKDOWN = "BREAKDOWN",
  NOT_AVAILABLE = "NOT_AVAILABLE"
}

export enum OperatorToMapEnum {
  YES = "YES",
  NO = "NO"
}

export enum PositionHandlingEnum {
  CROP = "CROP",
  FLOP = "FLOP",
  BO = "BO",
  LROP = "LROP"
}

export enum ManPowerViewInRequestFormEnum {
  YES = "YES",
  NO = "NO"
}

export enum BerthActualQty {
  QUANTITY_IN = "QUANTITY_IN",
  QUANTITY_OUT = "QUANTITY_OUT"
}

export enum BerthID {
  B1_1 = "B1_1",
  B1_2 = "B1_2",
  B1_3 = "B1_3",
  B1_4 = "B1_4",
  B2_1 = "B2_1",
  B2_2 = "B2_2",
  B2_3 = "B2_3",
  B2_4 = "B2_4",
  B2_5 = "B2_5",
  B3_1 = "B3_1",
  B3_2 = "B3_2",
  B3_3 = "B3_3",
  B3_4 = "B3_4",
  B3_5 = "B3_5",
  B4_1 = "B4_1",
  B4_2 = "B4_2",
  B4_3 = "B4_3",
  B4_4 = "B4_4",
  B4_5 = "B4_5",
  WW1_1 = "WW1_1",
  WW1_2 = "WW1_2",
  WW1_3 = "WW1_3",
  WW1_4 = "WW1_4",
  WW1_5 = "WW1_5",
  WW1_6 = "WW1_6",
  WW2_1 = "WW2_1",
  WW2_2 = "WW2_2",
  WW2_3 = "WW2_3",
  WW2_4 = "WW2_4",
  WW2_5 = "WW2_5",
  WW2_6 = "WW2_6",
  WW3_1 = "WW3_1",
  WW3_2 = "WW3_2",
  WW3_3 = "WW3_3",
  WW3_4 = "WW3_4",
  WW4_1 = "WW4_1",
  WW4_2 = "WW4_2",
  WW4_3 = "WW4_3",
  WW4_4 = "WW4_4",
  KTSB1_1 = "KTSB1_1"
}

export enum BerthMHERequestType {
  NORMAL = "NORMAL",
  CONSOLE = "CONSOLE"
}

export enum BerthName {
  KSB_BERTH_1 = "KSB_BERTH_1",
  KSB_BERTH_2 = "KSB_BERTH_2",
  KSB_BERTH_3 = "KSB_BERTH_3",
  KSB_BERTH_4 = "KSB_BERTH_4",
  KSB_BERTH_5 = "KSB_BERTH_5",
  KSB_BERTH_6 = "KSB_BERTH_6",
  KSB_BERTH_7 = "KSB_BERTH_7",
  WEST_WHARF_1 = "WEST_WHARF_1",
  WEST_WHARF_2 = "WEST_WHARF_2",
  WEST_WHARF_3 = "WEST_WHARF_3",
  WEST_WHARF_4 = "WEST_WHARF_4",
  KTSB = "KTSB"
}

export enum BerthPosition {
  ALONGSIDE = "ALONGSIDE",
  DOUBLE_BANK = "DOUBLE_BANK",
  TRIPLE_BANK = "TRIPLE_BANK",
  QUAD_BANK = "QUAD_BANK"
}

export enum BerthTerminal {
  KSB = "KSB",
  WW = "WW",
  KTSB = "KTSB"
}

export enum com_company_pbksb_entity_marine_BookingType {
  DAILY = "DAILY",
  RECURRING = "RECURRING"
}

export enum ChargeRate {
  ASQ = "ASQ",
  ASV = "ASV",
  ASB = "ASB"
}

export enum DocumentType {
  DELIVERY_ORDER = "DELIVERY_ORDER",
  OTHER_DOCUMENTS = "OTHER_DOCUMENTS",
  K4 = "K4",
  K5 = "K5"
}

export enum FullTank {
  YES = "YES",
  NO = "NO"
}

export enum GeneralWorkItem {
  INSPECTION = "INSPECTION",
  MAINTENANCE = "MAINTENANCE",
  STANDBY = "STANDBY",
  TOUCH_AND_GO = "TOUCH_AND_GO",
  MOORING = "MOORING",
  UNMOORING = "UNMOORING",
  FIREFIGHTER = "FIREFIGHTER",
  YOKOHAMA_FENDERS = "YOKOHAMA_FENDERS",
  GANGWAY_6M = "GANGWAY_6M",
  GANGWAY_10M = "GANGWAY_10M",
  GANGWAY_15M = "GANGWAY_15M",
  LOADING = "LOADING",
  DISCHARGE = "DISCHARGE",
  DISCHARGE_LOADING = "DISCHARGE_LOADING",
  OTHER_BULK = "OTHER_BULK",
  GARBAGE_REMOVAL_DUES = "GARBAGE_REMOVAL_DUES",
  CREW_CHANGE = "CREW_CHANGE",
  PNEUMATIC_RUBBER_FENDER = "PNEUMATIC_RUBBER_FENDER"
}

export enum HeavyPackages {
  _15_25_TONNES = "_15_25_TONNES",
  _25_50_TONNES = "_25_50_TONNES",
  _50_75_TONNES = "_50_75_TONNES",
  MORE_75_TONNES = "MORE_75_TONNES"
}

export enum MachineryConsoleItem {
  FORKLIFT_03T = "FORKLIFT_03T",
  PRIME_MOVER = "PRIME_MOVER",
  ROAD_SWEEPER_CF_60 = "ROAD_SWEEPER_CF_60"
}

export enum MarineServiceCode {
  WATERMAN = "WATERMAN",
  FUELMAN = "FUELMAN"
}

export enum MarineStatus {
  INITIATED = "INITIATED",
  BOOKED = "BOOKED",
  CANCELLED = "CANCELLED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  PENDING_AMENDMENT = "PENDING_AMENDMENT",
  ENDORSED = "ENDORSED",
  COMPLETED = "COMPLETED",
  VERIFIED = "VERIFIED",
  SENT = "SENT",
  PENDING_ENDORSEMENT_CANCELLED = "PENDING_ENDORSEMENT_CANCELLED",
  ENDORSED_CANCELLED = "ENDORSED_CANCELLED"
}

export enum MaterialRequisitionItem {
  B_CEMENT = "B_CEMENT",
  G_CEMENT = "G_CEMENT",
  BENTONITE = "BENTONITE",
  BARITE = "BARITE",
  OBM = "OBM",
  SBM = "SBM",
  BRINE = "BRINE",
  BASE_OIL = "BASE_OIL",
  OTHERS_BULK = "OTHERS_BULK"
}

export enum MaterialRequisitionServiceType {
  LOADING = "LOADING",
  DISCHARGE = "DISCHARGE",
  MIXING = "MIXING",
  CENTRIFUGE = "CENTRIFUGE",
  STORAGE = "STORAGE",
  SHEARING = "SHEARING"
}

export enum PrintStatus {
  YES = "YES",
  NO = "NO"
}

export enum ScopeWork {
  OIL_FIELD_EQUIPMENT = "OIL_FIELD_EQUIPMENT",
  CONTAINER = "CONTAINER",
  CASING_TUBING = "CASING_TUBING",
  WATER = "WATER",
  WATER_T = "WATER_T",
  FUEL = "FUEL",
  FUEL_T = "FUEL_T",
  OBM = "OBM",
  SBM = "SBM",
  BARITE = "BARITE",
  BENTONITE = "BENTONITE",
  CEMENT = "CEMENT",
  BRINE = "BRINE",
  BASE_OIL = "BASE_OIL",
  OTHERS_BULK = "OTHERS_BULK",
  SHIP_WATER = "SHIP_WATER",
  SHIP_FUEL = "SHIP_FUEL"
}

export enum ServiceCode {
  WATER = "WATER",
  FUEL = "FUEL"
}

export enum Shifting {
  SHIFTING_0 = "SHIFTING_0",
  ALONGSIDE = "ALONGSIDE",
  SHIFTING_1 = "SHIFTING_1",
  SHIFTING_2 = "SHIFTING_2",
  SHIFTING_3 = "SHIFTING_3",
  SHIFTING_4 = "SHIFTING_4"
}

export enum Supply {
  VESSEL = "VESSEL",
  OTHER = "OTHER"
}

export enum Tank {
  FUEL = "FUEL",
  WATER = "WATER"
}

export enum UnderdeckItem {
  OIL_FIELD_EQUIPMENT = "OIL_FIELD_EQUIPMENT",
  CONTAINER = "CONTAINER",
  CASING_TUBING = "CASING_TUBING",
  B_CEMENT = "B_CEMENT",
  G_CEMENT = "G_CEMENT",
  BENTONITE = "BENTONITE",
  BARITE = "BARITE",
  OBM = "OBM",
  SBM = "SBM",
  BRINE = "BRINE",
  BASE_OIL = "BASE_OIL",
  OTHERS_BULK = "OTHERS_BULK",
  SHIP_FUEL = "SHIP_FUEL",
  SHIP_WATER = "SHIP_WATER"
}

export enum WorkPermitItem {
  ALL = "ALL",
  TANK_CLEANING = "TANK_CLEANING",
  WELDING_CUTTING = "WELDING_CUTTING",
  CONFINED_SPACE = "CONFINED_SPACE",
  HOT_WORK = "HOT_WORK",
  COLD_WORK = "COLD_WORK",
  DIVING = "DIVING"
}

export enum WorkProgram {
  MOORING = "MOORING",
  UNMOORING = "UNMOORING",
  GARBAGE_REMOVAL_DUES = "GARBAGE_REMOVAL_DUES",
  DISCHARGE = "DISCHARGE",
  LOADING = "LOADING",
  DISCHARGE_LOADING = "DISCHARGE_LOADING",
  INSPECTION = "INSPECTION",
  MAINTENANCE = "MAINTENANCE",
  STANDBY = "STANDBY",
  TOUCH_AND_GO = "TOUCH_AND_GO",
  CREW_CHANGE = "CREW_CHANGE",
  FUEL_WATER = "FUEL_WATER",
  GENERAL_WORKS = "GENERAL_WORKS",
  UNDERDECK = "UNDERDECK",
  SCOPE_WORK = "SCOPE_WORK",
  WORK_PERMIT = "WORK_PERMIT",
  FIREFIGHTER = "FIREFIGHTER",
  YOKOHAMA_FENDERS = "YOKOHAMA_FENDERS",
  GANGWAY_6M = "GANGWAY_6M",
  GANGWAY_10M = "GANGWAY_10M",
  GANGWAY_15M = "GANGWAY_15M",
  MOB_DEMOB = "MOB_DEMOB",
  LEVY_YOKOHAMA_FENDERS = "LEVY_YOKOHAMA_FENDERS",
  PNEUMATIC_RUBBER_FENDER = "PNEUMATIC_RUBBER_FENDER"
}

export enum WorkProgramType {
  DISCHARGE = "DISCHARGE",
  LOADING = "LOADING",
  DISCHARGE_LOADING = "DISCHARGE_LOADING"
}

export enum ModuleCode {
  SCHEDULED_WASTE_MANAGEMENT = "SCHEDULED_WASTE_MANAGEMENT",
  WASTE_DISPOSAL = "WASTE_DISPOSAL",
  CENTRALIZED_FOOD_SERVICES = "CENTRALIZED_FOOD_SERVICES",
  INTEGRATED_CHEMICAL_WAREHOUSE = "INTEGRATED_CHEMICAL_WAREHOUSE",
  COMMON_WAREHOUSE_COMMON_YARD = "COMMON_WAREHOUSE_COMMON_YARD",
  INTEGRATED_CHEMICAL_YARD = "INTEGRATED_CHEMICAL_YARD",
  MACHINERY_HANDLING_EQUIPMENT = "MACHINERY_HANDLING_EQUIPMENT",
  PETROLEUM_SUPPLY_BASE = "PETROLEUM_SUPPLY_BASE",
  MARINE = "MARINE",
  PROPERTY_RENTAL = "PROPERTY_RENTAL",
  CREW_TRANSFER = "CREW_TRANSFER"
}

export enum OddSizeCargoType {
  LOADING = "LOADING",
  UNLOADING = "UNLOADING"
}

export enum DisplayInRequestForm {
  YES = "YES",
  NO = "NO"
}

export enum Gang_Type {
  A = "A",
  B = "B"
}

export enum Operator_Type {
  BASE_OPERATOR = "BASE_OPERATOR",
  CHARGEHAND_OPERATOR = "CHARGEHAND_OPERATOR",
  CRANE_OPERATOR = "CRANE_OPERATOR",
  FORKLIFT_OPERATOR = "FORKLIFT_OPERATOR",
  EQUIPMENT_OPERATOR = "EQUIPMENT_OPERATOR",
  PRIMEMOVER_OPERATOR = "PRIMEMOVER_OPERATOR",
  FIRE_FIGHTER = "FIRE_FIGHTER",
  FOREMAN = "FOREMAN",
  GANG = "GANG",
  LORRY_OPERATOR = "LORRY_OPERATOR"
}

export enum OutboundSoDocumentType {
  WASTE_CARD = "WASTE_CARD",
  CONSIGNMENT_NOTE = "CONSIGNMENT_NOTE",
  CUSTOMS_APPROVAL_LETTER = "CUSTOMS_APPROVAL_LETTER",
  RECEIVERS_DOE_LICENSE = "RECEIVERS_DOE_LICENSE",
  OTHERS = "OTHERS"
}

export enum BranchCode {
  CHE = "CHE"
}

export enum ChargeCycle {
  DAILY = "DAILY",
  MONTHLY = "MONTHLY"
}

export enum CompanyCode {
  PBKSB = "PBKSB",
  EOS = "EOS",
  KSB01 = "KSB01"
}

export enum InvoiceType {
  CREDIT = "CREDIT",
  INVOICE = "INVOICE"
}

export enum PriceScheduleType {
  MHE = "MHE",
  CHE = "CHE",
  OTHERS = "OTHERS"
}

export enum RateCode {
  A = "A",
  B = "B",
  C = "C",
  D = "D",
  NONE = "NONE"
}

export enum ScopeOfWorkItem {
  CHARGE_RATE_A = "CHARGE_RATE_A",
  CHARGE_RATE_B = "CHARGE_RATE_B",
  CHARGE_RATE_C = "CHARGE_RATE_C",
  CHARGE_RATE_D = "CHARGE_RATE_D"
}

export enum ServiceType {
  MHE = "MHE",
  DVO = "DVO"
}

export enum TaxCode {
  SSO = "SSO"
}

export enum UOM {
  HOUR = "HOUR",
  MONTH = "MONTH",
  DAILY = "DAILY",
  PER_JOB_TICKET = "PER_JOB_TICKET",
  OPERATION = "OPERATION",
  VESSEL = "VESSEL",
  BBL = "BBL",
  METRIC_TAN = "METRIC_TAN",
  UNIT = "UNIT",
  DAY = "DAY"
}

export enum WeekendStatus {
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY"
}

export enum Category_Type {
  BONDED = "BONDED",
  LOCAL = "LOCAL"
}

export enum Exceed_Limit_Status {
  TRUE = "TRUE",
  FALSE = "FALSE"
}

export enum Form_Type {
  K1 = "K1",
  K2 = "K2",
  K3 = "K3",
  K4 = "K4",
  K5 = "K5",
  K8 = "K8",
  K9 = "K9",
  F4 = "F4",
  F5 = "F5",
  DELIVERY_ORDER = "DELIVERY_ORDER",
  PURCHASE_ORDER = "PURCHASE_ORDER",
  JDA1 = "JDA1",
  JDA2 = "JDA2",
  JDA3 = "JDA3",
  MANIFEST = "MANIFEST",
  CIPL = "CIPL",
  COG = "COG",
  OTHERS = "OTHERS"
}

export enum Good_Category {
  LOCAL = "LOCAL",
  BONDED = "BONDED"
}

export enum Good_In_Statu {
  INITIATED = "INITIATED",
  IN_PROGRESS = "IN_PROGRESS",
  APPROVED = "APPROVED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  CANCEL = "CANCEL",
  DELETED = "DELETED",
  INCOMPLETE = "INCOMPLETE",
  COMPLETED = "COMPLETED",
  PENDING_ADJUSTMENT_APPROVAL = "PENDING_ADJUSTMENT_APPROVAL",
  ADJUSTMENT_APPROVED = "ADJUSTMENT_APPROVED",
  SUBMITTED = "SUBMITTED",
  RETURNED = "RETURNED",
  ON_HOLD = "ON_HOLD",
  OVERRIDE = "OVERRIDE",
  TEMPORARY_OUT = "TEMPORARY_OUT",
  REJECTED = "REJECTED"
}

export enum Good_Type {
  TYPE_1 = "TYPE_1",
  TYPE_2 = "TYPE_2",
  TYPE_3 = "TYPE_3"
}

export enum GoodDescriptionsEnum {
  EXISTING = "EXISTING",
  NEW = "NEW"
}

export enum Job_status {
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ASSIGNED = "ASSIGNED",
  AVAILABLE = "AVAILABLE",
  CANCELLED = "CANCELLED",
  UNASSIGNED = "UNASSIGNED"
}

export enum Location {
  WAREHOUSE_1 = "WAREHOUSE_1",
  WAREHOUSE_2 = "WAREHOUSE_2",
  WAREHOUSE_3 = "WAREHOUSE_3"
}

export enum Return_Status {
  PARTIAL_RETURN = "PARTIAL_RETURN",
  COMPLETE_RETURN = "COMPLETE_RETURN",
  PENDING_RETURN = "PENDING_RETURN"
}

export enum Status {
  DRAFT = "DRAFT",
  IN_PROGRESS = "IN_PROGRESS",
  APPROVED = "APPROVED",
  REJECT = "REJECT",
  INCOMPLETE = "INCOMPLETE",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED"
}

export enum Storage {
  WAREHOUSE_1 = "WAREHOUSE_1",
  WAREHOUSE_2 = "WAREHOUSE_2",
  WAREHOUSE_3 = "WAREHOUSE_3"
}

export enum Transaction_Form_Type {
  GOOD_IN = "GOOD_IN",
  RETURN_GOOD = "RETURN_GOOD",
  TRANSFER_OWNERSHIP = "TRANSFER_OWNERSHIP",
  TRANSFER_LOCATION = "TRANSFER_LOCATION",
  BUILD_PART = "BUILD_PART"
}

export enum Transaction_PSB_Type {
  GOODS_IN = "GOODS_IN",
  GOODS_OUT = "GOODS_OUT",
  TRANSFER_OWNERSHIP = "TRANSFER_OWNERSHIP",
  TRANSFER_LOCATION = "TRANSFER_LOCATION",
  BUILD_FROM_PARTS = "BUILD_FROM_PARTS"
}

export enum Transaction_Type {
  ISSUE_OUT = "ISSUE_OUT",
  TEMPORARY = "TEMPORARY"
}

export enum Type_Of_Goods {
  DANGEROUS_CHEMICAL = "DANGEROUS_CHEMICAL",
  PETROLEUM = "PETROLEUM",
  OTHERS = "OTHERS"
}

export enum PeriodStart {
  ONEAM = "ONEAM",
  TWOAM = "TWOAM"
}

export enum RentalUOMEnum {
  DAY = "DAY"
}

export enum RamadhanCalander {
  YES = "YES"
}

export enum RequestCFSStatus {
  SUBMITTED = "SUBMITTED",
  CANCELLED = "CANCELLED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ENDORSED = "ENDORSED",
  CHECKED = "CHECKED",
  SENT = "SENT",
  COMPLETED = "COMPLETED"
}

export enum RequestCFSType {
  STORAGE = "STORAGE",
  LOADING_CABLING = "LOADING_CABLING",
  HOUSEKEEPING_CLEANING_STUFFING = "HOUSEKEEPING_CLEANING_STUFFING",
  PLUG_ON_OFF = "PLUG_ON_OFF",
  REPAIR = "REPAIR",
  HANDLING_FEE_TRANSPORT = "HANDLING_FEE_TRANSPORT",
  OTHER_ACTIVITIES = "OTHER_ACTIVITIES"
}

export enum com_company_pbksb_entity_requestform_BookingType {
  DAILY = "DAILY",
  RECURRING = "RECURRING",
  CONTRACT = "CONTRACT"
}

export enum RequestFormStatus {
  SUBMIT = "SUBMIT",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_LIST = "WAITING_LIST",
  BOOKED = "BOOKED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  ENDORSED = "ENDORSED",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  PAID_CASH = "PAID_CASH",
  INITIATED = "INITIATED",
  ON_HOLD = "ON_HOLD"
}

export enum RequestServiceType {
  NORMAL = "NORMAL",
  CONSOLE = "CONSOLE"
}

export enum RequestStatus {
  SUBMITTED = "SUBMITTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ENDORSED = "ENDORSED",
  CANCELLED = "CANCELLED"
}

export enum ScheduledWasteEnum {
  INITIATE = "INITIATE",
  SUBMITTED = "SUBMITTED",
  CANCELED = "CANCELED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ENDORSED = "ENDORSED"
}

export enum ScheduledWasteRepackagingType {
  BUNG_HOLE_DRUM_LIQUID = "BUNG_HOLE_DRUM_LIQUID",
  OPEN_TOP_DRUM_SOLID_SLUDGE = "OPEN_TOP_DRUM_SOLID_SLUDGE",
  IBC_TANK_LIQUID = "IBC_TANK_LIQUID",
  IBC_TANK_LIQUID_SLUDGE = "IBC_TANK_LIQUID_SLUDGE",
  TOTE_TANK_LIQUID = "TOTE_TANK_LIQUID",
  JUMBO_BAG_SOLID_SLUDGE = "JUMBO_BAG_SOLID_SLUDGE",
  WOODEN_BOXES_SOLID = "WOODEN_BOXES_SOLID",
  OTHERS = "OTHERS"
}

export enum ScheduledWasteStorageItems {
  PALLET = "PALLET",
  DRUMS = "DRUMS",
  JUMBO_BAG = "JUMBO_BAG",
  BOX = "BOX",
  IBC_TANK = "IBC_TANK",
  JERRYCAN_CARBOY = "JERRYCAN_CARBOY",
  OTHERS = "OTHERS"
}

export enum ScheduledWasteStorageType {
  DRY_STORAGE = "DRY_STORAGE",
  WET_STORAGE = "WET_STORAGE"
}

export enum ScheduledWasteType {
  INBOUND = "INBOUND",
  OUTBOUND = "OUTBOUND"
}

export enum ScheduledWasteUOM {
  PALLET = "PALLET",
  TRIP = "TRIP",
  UNIT = "UNIT",
  HOUR = "HOUR",
  TONNE = "TONNE"
}

export enum ScheduledWasteUomEnum {
  STEEL_BUNG_HOLE_DRUM = "STEEL_BUNG_HOLE_DRUM",
  PLASTIC_BUNG_HOLE_DRUM = "PLASTIC_BUNG_HOLE_DRUM",
  STEEL_OPEN_TOP_DRUM = "STEEL_OPEN_TOP_DRUM",
  PLASTIC_OPEN_TOP_DRUM = "PLASTIC_OPEN_TOP_DRUM",
  WOODEN_BOX_4X4X4 = "WOODEN_BOX_4X4X4",
  WOODEN_BOX_4X8X4 = "WOODEN_BOX_4X8X4",
  TOTE_TANK = "TOTE_TANK",
  IBC = "IBC",
  JUMBO_BAG = "JUMBO_BAG",
  PALLET = "PALLET",
  OTHERS = "OTHERS"
}

export enum SiteCategory {
  ALL = "ALL",
  OTHERS = "OTHERS",
  PIERS = "PIERS",
  WAREHOUSE = "WAREHOUSE",
  YARD = "YARD",
  BERTH = "BERTH"
}

export enum SiteViewInListBoxEnum {
  YES = "YES",
  NO = "NO"
}

export enum SpaceType {
  WAREHOUSE = "WAREHOUSE",
  OFFICE = "OFFICE",
  OPEN_YARD = "OPEN_YARD"
}

export enum SpaceRentalStatusEnums {
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  CANCELED = "CANCELED",
  TERMINATED = "TERMINATED"
}

export enum SWScopeOfServices {
  STORAGE = "STORAGE",
  HANDLING_IN_INBOUND = "HANDLING_IN_INBOUND",
  HANDLING_OUT_OUTBOUND = "HANDLING_OUT_OUTBOUND",
  COLLECTION_PRIMEMOVER_OPERATOR = "COLLECTION_PRIMEMOVER_OPERATOR",
  RETURN_SKID_PRIMEMOVER_OPERATOR = "RETURN_SKID_PRIMEMOVER_OPERATOR",
  REPACKAGING_FROM_DRUMS_SOLID_SLUDGE_OPEN_TOP = "REPACKAGING_FROM_DRUMS_SOLID_SLUDGE_OPEN_TOP",
  REPACKAGING_FROM_DRUM_LIQUID_BUNG_HOLE = "REPACKAGING_FROM_DRUM_LIQUID_BUNG_HOLE",
  REPACKAGING_FROM_IBC_TANK_LIQUID = "REPACKAGING_FROM_IBC_TANK_LIQUID",
  REPACKAGING_FROM_IBC_TANK_LIQUID_SLUDGE = "REPACKAGING_FROM_IBC_TANK_LIQUID_SLUDGE",
  REPACKAGING_FROM_TOT_TANK_LIQUID = "REPACKAGING_FROM_TOT_TANK_LIQUID",
  REPACKAGING_FROM_JUMBO_BAG_SOLID_SLUDGE = "REPACKAGING_FROM_JUMBO_BAG_SOLID_SLUDGE",
  REPACKAGING_FROM_WOODEN_BOXES_SOLID = "REPACKAGING_FROM_WOODEN_BOXES_SOLID",
  PACKING_PALLETIZING_STRAPPING_DRUMS = "PACKING_PALLETIZING_STRAPPING_DRUMS",
  PACKING_PALLETIZING_STRAPPING_PALLET = "PACKING_PALLETIZING_STRAPPING_PALLET",
  WEIGHING = "WEIGHING",
  DRUM_CRUSHING_SERVICE = "DRUM_CRUSHING_SERVICE",
  UNLOADING_ODD_SIZE_CARGO = "UNLOADING_ODD_SIZE_CARGO",
  LOADING_ODD_SIZE_CARGO = "LOADING_ODD_SIZE_CARGO",
  STEEL_BUNGHOLE_DRUM = "STEEL_BUNGHOLE_DRUM",
  STEEL_OPEN_TOP_DRUM = "STEEL_OPEN_TOP_DRUM",
  HDPE_BUNGHOLE_DRUM = "HDPE_BUNGHOLE_DRUM",
  HDPE_OPEN_TOP_DRUM = "HDPE_OPEN_TOP_DRUM",
  IBC_TANK = "IBC_TANK",
  WOODEN_BOX_4X4X4 = "WOODEN_BOX_4X4X4",
  WOODEN_BOX_4X8X4 = "WOODEN_BOX_4X8X4",
  JUMBO_BAG_1_TON = "JUMBO_BAG_1_TON",
  PALLET_OTHERS = "PALLET_OTHERS",
  SW_102 = "SW_102",
  SW_103 = "SW_103",
  SW_104 = "SW_104",
  SW_110 = "SW_110",
  SW_305 = "SW_305",
  SW_306 = "SW_306",
  SW_307 = "SW_307",
  SW_311 = "SW_311",
  SW_404 = "SW_404",
  SW_408 = "SW_408",
  SW_409 = "SW_409",
  SW_410 = "SW_410",
  SW_417 = "SW_417",
  SW_421 = "SW_421",
  SW_422 = "SW_422",
  SW_429 = "SW_429",
  SW_501 = "SW_501"
}

export enum TripStatusEnum {
  INITIATED = "INITIATED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED"
}

export enum TwgEnum {
  INITIATE = "INITIATE",
  APPROVED = "APPROVED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  REJECTED = "REJECTED"
}

export enum WasteDisposalEnum {
  SUBMITTED = "SUBMITTED",
  CANCELED = "CANCELED",
  IN_PROGRESS = "IN_PROGRESS",
  PENDING_ENDORSEMENT = "PENDING_ENDORSEMENT",
  ENDORSED = "ENDORSED",
  CHECKED = "CHECKED"
}

export enum WasteDisposalPriceUnit {
  SKID = "SKID",
  DAY = "DAY"
}

export enum WasteDisposalType {
  NORMAL = "NORMAL",
  STORAGE = "STORAGE"
}
