import { RequestLine } from "./pbksb_RequestLine";
export class RequestPlugOnLine extends RequestLine {
  static NAME = "pbksb_RequestPlugOnLine";
}
export type RequestPlugOnLineViewName = "_base" | "_local" | "_minimal";
export type RequestPlugOnLineView<
  V extends RequestPlugOnLineViewName
> = V extends "_base"
  ? Pick<
      RequestPlugOnLine,
      | "id"
      | "container"
      | "requestType"
      | "storageBillingStatus"
      | "lastBilled"
      | "containerNumber"
      | "containerType"
      | "repairRequest"
      | "cablingOnVessel"
      | "fourCoreDNV"
      | "repair"
      | "lotNumber"
      | "storageStartDate"
      | "storageEndDate"
      | "plugOnDate"
      | "plugOffDate"
      | "plugOn"
      | "plugOff"
      | "remarks"
      | "location"
      | "temperatureReading"
      | "temperatureStart"
      | "temperature"
      | "requestTicketNumber"
      | "housekeepingRequired"
      | "cleaningRequired"
      | "stuffingRequired"
      | "outsideInsideBonded"
      | "containerReturn"
      | "time"
      | "status"
      | "completedDateTime"
    >
  : V extends "_local"
  ? Pick<
      RequestPlugOnLine,
      | "id"
      | "requestType"
      | "storageBillingStatus"
      | "lastBilled"
      | "containerNumber"
      | "containerType"
      | "repairRequest"
      | "cablingOnVessel"
      | "fourCoreDNV"
      | "repair"
      | "lotNumber"
      | "storageStartDate"
      | "storageEndDate"
      | "plugOnDate"
      | "plugOffDate"
      | "plugOn"
      | "plugOff"
      | "remarks"
      | "location"
      | "temperatureReading"
      | "temperatureStart"
      | "temperature"
      | "requestTicketNumber"
      | "housekeepingRequired"
      | "cleaningRequired"
      | "stuffingRequired"
      | "outsideInsideBonded"
      | "containerReturn"
      | "time"
      | "status"
      | "completedDateTime"
    >
  : V extends "_minimal"
  ? Pick<RequestPlugOnLine, "id" | "container">
  : never;
